### ISSUE TITLE
How do I use xsvd-js to add new registers to qemu-arm-xpack?

### ISSUE THREAD

**Issue by webic** [xpack-dev-tools/qemu#10]
I used xsvd-js to make a lot of .c & .h file, but I don't know how to use them to add new registers to qemu-arm-xpack.

**Comment by ilg-ul** [comment]
For questions and general support, please use the project forums.

**Comment by webic** [comment]
Thankyou very much! I think I have found the answer I want.
https://www.tapatalk.com/groups/xpack/viewtopic.php?p=677#p677
